### ISSUE TITLE
Don't require HTTPS Decryption

### ISSUE THREAD

**Issue by vcsjones** [vcsjones/FiddlerCert#10]
Currently FiddlerCert only works if HTTPS traffic decryption is enabled. This should not be a requirement as it should still be able to show the certificate chain in CONNECT tunnels.

@ericlaw1979 Is the `SessionFlags.IsBlindTunnel` the right way to check if a CONNECT tunnel is for an HTTPS connection that doesn't have traffic decryption? My "Should I show certificate" check looks like this right now:

```
if (oS.isHTTPS || (oS.BitFlags & SessionFlags.IsDecryptingTunnel) == SessionFlags.IsDecryptingTunnel || (oS.BitFlags & SessionFlags.IsBlindTunnel) == SessionFlags.IsBlindTunnel)
{
     //Do fascinating things
}
```

**Comment by ericlaw1979** [comment]
A tunnel is a Decrypting tunnel if it's using HTTPS. It's a BlindTunnel if Fiddler is just shuffling bytes back and forth-- note that beyond HTTPS, I'm pretty sure WebSocket traffic can be going through a BlindTunnel too (if you don't have message parsing enabled).

So, you can write things like this:
`if (oS.isAnyFlagSet(SessionFlags.IsWebSocketTunnel | SessionFlags.IsBlindTunnel | SessionFlags.IsDecryptingTunnel)) {`

**Comment by vcsjones** [comment]
OK, my previous assumptions were wrong.

The issue I am running into is when "Capture HTTPS CONNECTs" is checked but "Decrypt HTTPS traffic" is not. It appears that in these circumstances, Fiddler does not fire the `FiddlerApplication.OnValidateServerCertificate`.

That makes sense - Fiddler shouldn't need to validate the certificate if it is just acting as a dumb pipe. It should be possible to capture the certificate from the Server Hello, however. Is there a way to do this in Fiddler?

**Comment by ericlaw1979** [comment]
> It should be possible to capture the certificate from the Server Hello, however. Is there a way to do this in Fiddler?

Not presently, no. FiddlerCore has an OnReadResponseBuffer event but this isn't called by Fiddler for performance reasons.
