### ISSUE TITLE
Show Certificate Info on CONNECT Tunnel

### ISSUE THREAD

**Issue by ericlaw1979** [vcsjones/FiddlerCert#2]
Seems like the Certificate info should be shown when a Tunnel is selected?

If it can't be for whatever reason (or on a HTTP site) maybe show an explanatory text label?

**Comment by vcsjones** [comment]
I don't know where to grab the certificate on a tunnel. [Currently](https://github.com/vcsjones/FiddlerCert/blob/master/VCSJones.FiddlerCert/CertificateInspector.cs#L32) I am doing it in AutoTamperResponseBefore, and I don't see the cert there.

I will add explanatory text for HTTP connections and other situations where there are no certificates to display.

**Comment by ericlaw1979** [comment]
Yeah, I only realized later why this is hard. When the Tunnel completes, there isn't any HTTPS traffic on it yet, which means no handshake, which means nothing to parse. 

The sequence of events around tunnels is really intricate, and I should probably introduce a new event for this scenario. Today, if fiddler.network.https.storeservercertchain is set, the server certificates are emitted as text in the responseBody, but maybe these should just set your base64'd property on the tunnel?

**Comment by vcsjones** [comment]
I saw that the responseBody contains a partial piece of the certificate, if the certificate gets set somewhere on the session I can grab it.

I can also do some evil reflection to grab the certificate in the inspector, but that is well, evil. At the point in the inspector, I could do:

```
if (session.bitFlags.HasFlag(Fiddler.SessionFlags.IsDecryptingTunnel))
{
     //Assume everything is public
     var cert = session.__oTunnel.pipeTunnelRemote.ServerCertificate;
}
```

Could that ServerCertificate just be made public somewhere?

**Comment by ericlaw1979** [comment]
responseBody shouldn't ever contain a piece of the certificate, unless you're referring to the textual representation placed there by the Fiddler code that describes the connection security?

The problem with grabbing the .ServerCertificate off of pipeTunnelRemote (or similar methods) is that the certificate isn't available after the connection is closed (today). It probably makes sense for Fiddler to keep a copy on the tunnel itself; I didn't do this in the past only to reduce memory use.

**Comment by vcsjones** [comment]
> responseBody shouldn't ever contain a piece of the certificate, unless you're referring to the textual representation placed there by the Fiddler code that describes the connection security?

Yes.

> It probably makes sense for Fiddler to keep a copy on the tunnel itself; I didn't do this in the past only to reduce memory use.

Yeah, or event where I can safely copy it myself. That way it only hangs in memory for extensions that need it. I could easily have done this:

```
var cert = new X509Certificate2(session.__oTunnel.pipeTunnelRemote.ServerCertificate);
```

That will duplicate the certificate context.

**Comment by ericlaw1979** [comment]
Haha... it occurs to me that this already exists.

FiddlerApplication.OnValidateServerCertificate += FiddlerApplication_OnValidateServerCertificate;

private void FiddlerApplication_OnValidateServerCertificate(object sender, ValidateServerCertificateEventArgs e)
        {
        }     

The eventargs contain both the certificate and the session.

**Comment by vcsjones** [comment]
Oh and it even gives me the chain that the server sent and the policy errors. This way I don't need to build my own chain that relies on the certificate store to get the chain.

**Comment by ericlaw1979** [comment]
To be clear here, I'm pretty sure the "chain" it gives you is fundamentally the same thing that you constructed your way, .NET is just doing it on your behalf.

**Comment by vcsjones** [comment]
Curious: what happens if a server sends an intermediate certificate that isn't in the Windows certificate store? I think the X509Chain would fail to build a chain down to the root even though the browser could because the server sent a complete chain.

**Comment by ericlaw1979** [comment]
It'd be interesting to try it, but ultimately most of the .NET stuff goes down through SChannel/CAPI anyway so I'd be surprised if something that IE accepted didn't work in .NET code. Thus far, I've never seen any reports of such problems.
